import re
from typing import List

from pydantic import BaseModel, Field, field_validator

# ---------------------------------------------------------------------------
# DB2 tag vocabulary — MACHINE-DERIVED from the live aviation-library-v2 store.
# Generated by `scripts/derive_db2_vocabulary.py` (2026-06-19, live DB2 = 27 docs). Do NOT
# hand-edit: re-run that script after any DB2 change and paste its output here. Each token is
# the document-tag derived from a live DB2 document's filename.
# ---------------------------------------------------------------------------
DB2_VOCABULARY = {
    '14 CFR 61', '14 CFR 67', '14 CFR 68', '14 CFR 91',
    'AC 00-45H', 'AC 60-22', 'AC 61-142', 'AC 61-67C', 'AC 61-98E',
    'AC 68-1', 'AC 68-1A', 'AC 90-48E', 'AC 90-66C', 'AC 91-67',
    'AC 91-73B', 'AC 91-92', 'AIM',
    'FAA-H-8083-15B', 'FAA-H-8083-1B', 'FAA-H-8083-2', 'FAA-H-8083-25',
    'FAA-H-8083-28', 'FAA-H-8083-3C', 'FAA-S-ACS-6C',
}


def normalize_key(raw: str) -> str:
    """Strip corruption from a reference key while preserving the underlying reference.

    Removes: leading ``**``/``*`` markdown bleed, ``[cite: N]`` extraction artifacts,
    and a trailing ``(annotation)`` (e.g. ``FAA-H-8083-25C (PHAK)`` -> ``FAA-H-8083-25C``,
    ``AC 120-12A (Private vs Common Carriage)`` -> ``AC 120-12A``). Does NOT drop the key.
    """
    k = str(raw).strip().lstrip('*').strip()
    k = re.sub(r'\[cite:[^\]]*\]', '', k).strip()
    k = re.sub(r'\s*\([^)]*\)\s*$', '', k).strip()   # closed trailing annotation
    k = re.sub(r'\s*\([^)]*$', '', k).strip()         # UNclosed trailing annotation, e.g. "(AFH Ch 6"
    # Strip a sentence-terminating period (e.g. "14 CFR 91.103.") but preserve
    # initialisms like "U.S." — only when the period follows a digit or lowercase letter.
    k = re.sub(r'(?<=[a-z0-9])\.$', '', k)
    return k.strip()


def is_garbage(k: str) -> bool:
    """True for fragments that carry no reference value: empty, ``N/A``, orphaned
    chapter fragments (``Ch 8``, ``Ch 9)``, ``Chapter 17``), or pure punctuation."""
    if not k or k.upper() == 'N/A':
        return True
    if re.fullmatch(r'(?:Ch|Chapter)\s*\d+\)?', k, re.IGNORECASE):
        return True
    if re.fullmatch(r'[\W_]+', k):
        return True
    return False


def to_family(k: str) -> str:
    """Normalize a reference to its document-FAMILY token for DB2 matching — edition
    suffixes are dropped so the curriculum (``AC 61-98D``, ``FAA-H-8083-25C``) lines up
    with the library (``AC 61-98E``, ``FAA-H-8083-25``)."""
    k = normalize_key(k)
    m = re.match(r'(FAA-S-ACS-\d+)', k)
    if m:
        return m.group(1)
    m = re.match(r'(FAA-[A-Z]-\d+(?:-\d+)?)', k)  # trailing edition letter excluded
    if m:
        return m.group(1)
    m = re.match(r'AC\s+(\d+(?:\.\d+)?-\d+)', k)   # AC 61-98D -> AC 61-98
    if m:
        return f"AC {m.group(1)}"
    m = re.match(r'(?:\d+\s*CFR)\s*(?:part\s*)?(\d+)', k, re.IGNORECASE)
    if m:
        return f"14 CFR {m.group(1)}"
    if 'AIM' in k.upper():
        return 'AIM'
    return k


def is_document_level(k: str) -> bool:
    """True if a key names a whole document (``FAA-H-8083-25C``, ``AC 61-98D``, ``AIM``) rather
    than a chapter/section within one (``FAA-H-8083-3C Chapter 18``, ``AIM 8-1-5``, ``(PHAK Ch 5``).
    Used to keep DB2 ``document_tags`` document-level — sub-references stay as display-only keys."""
    k = normalize_key(k)
    if re.search(r'\b(?:Ch|Chapter|Section|Sec|Appendix)\b', k, re.IGNORECASE):
        return False
    if '(' in k or ')' in k:
        return False
    if re.match(r'AIM\s+\d', k):  # AIM 8-1-5 is a section; bare "AIM" is the document
        return False
    return True


def to_document_level(k: str) -> str:
    """Reduce a sub-document reference to its whole-document token so it can bridge:
    ``FAA-H-8083-25C Chapter 6`` -> ``FAA-H-8083-25C``, ``AIM 5-1-4`` -> ``AIM``. Returns the
    key unchanged if it is already document-level."""
    k = normalize_key(k)
    if is_document_level(k):
        return k
    stripped = re.sub(r'\s+(?:Ch|Chapter|Section|Sec|Appendix)\b.*$', '', k, flags=re.IGNORECASE).strip()
    if stripped and is_document_level(stripped):
        return normalize_key(stripped)   # normalize away any annotation, e.g. "(PHAK)"
    return to_family(k)


DB2_FAMILIES = {to_family(t) for t in DB2_VOCABULARY}


def coverage(doc_keys: List[str]) -> tuple[List[str], List[str]]:
    """Split clean doc_keys into (covered_by_DB2, reference_only). Reference-only keys
    are kept and valid — they are student-facing citations that simply don't bridge."""
    covered = [k for k in doc_keys if to_family(k) in DB2_FAMILIES]
    reference_only = [k for k in doc_keys if to_family(k) not in DB2_FAMILIES]
    return covered, reference_only


class ContentSource(BaseModel):
    mimeType: str
    uri: str


class CurriculumStructData(BaseModel):
    acs_code: str
    title: str
    type: str
    ancestral_context: str
    reg_keys: List[str]
    doc_keys: List[str] = Field(..., min_length=1)
    keywords: List[str]

    @field_validator('reg_keys', 'doc_keys', 'keywords', mode='before')
    @classmethod
    def clean_keys(cls, v):
        """Normalize every key and drop garbage fragments — never silently drop a real
        reference. Keys absent from DB2 are kept (decision 2026-06-18: keys double as
        student-facing references)."""
        if not v:
            return []
        out: List[str] = []
        for x in v:
            k = normalize_key(x)
            if is_garbage(k):
                continue
            if k not in out:
                out.append(k)
        return out


class CurriculumLessonSchema(BaseModel):
    """A single curriculum lesson (DB1). Reads the standalone .json metadata sidecar.
    Does not include `content` (appended when generating the JSONL)."""
    id: str
    structData: CurriculumStructData


class LibraryStructData(BaseModel):
    category: str  # 'regulation' | 'handbook' | 'advisory_circular'
    title: str
    subfolder: str
    filename: str

    @field_validator('category')
    @classmethod
    def validate_category(cls, v: str) -> str:
        allowed = {'regulation', 'handbook', 'advisory_circular'}
        if v not in allowed:
            raise ValueError(f"Category must be one of {allowed}")
        return v


class LibraryMetadataSchema(BaseModel):
    """A single library document (DB2)."""
    id: str
    structData: LibraryStructData


# Vertex AI Search JSONL output schemas


class VertexCurriculumEntry(BaseModel):
    id: str
    structData: CurriculumStructData
    content: ContentSource


class VertexLibraryEntry(BaseModel):
    id: str
    structData: LibraryStructData
    content: ContentSource
