import os
import ast
from pathlib import Path

# Configuration
PROJECT_ROOT = Path(__file__).parent.parent
OUTPUT_FILE = PROJECT_ROOT / "_docs" / "docs_prds" / "repo-map.md"

IGNORE_DIRS = {
    ".git", ".venv", "venv", "__pycache__", "node_modules",
    ".agent", ".claude", ".gemini", "auth_keys",
    "_artifacts", "_claude_artifacts", "_opencode_artifacts",
    "_test_scripts", ".pytest_cache",
}

def generate_ast_summary(filepath):
    """Parses a Python file and extracts class and function signatures."""
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            code = f.read()
            tree = ast.parse(code, filename=str(filepath))
    except Exception as e:
        return [f"    [Error parsing AST: {e}]"]

    lines = []
    for node in tree.body:
        if isinstance(node, ast.ClassDef):
            lines.append(f"    class {node.name}:")
            methods = [n for n in node.body if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef))]
            for method in methods:
                # Extract arguments simply
                args = [arg.arg for arg in method.args.args]
                args_str = ", ".join(args)
                lines.append(f"        def {method.name}({args_str})")
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            args = [arg.arg for arg in node.args.args]
            args_str = ", ".join(args)
            prefix = "async def" if isinstance(node, ast.AsyncFunctionDef) else "def"
            lines.append(f"    {prefix} {node.name}({args_str})")
            
    return lines

def walk_directory(directory, prefix=""):
    """Recursively walks the directory and builds the map string."""
    map_lines = []
    
    try:
        entries = sorted(os.listdir(directory))
    except PermissionError:
        return []

    # Filter out ignored directories
    entries = [e for e in entries if e not in IGNORE_DIRS]
    
    for i, entry in enumerate(entries):
        is_last = (i == len(entries) - 1)
        path = os.path.join(directory, entry)
        
        # Tree drawing characters
        connector = "└── " if is_last else "├── "
        map_lines.append(f"{prefix}{connector}{entry}")
        
        if os.path.isdir(path):
            extension = "    " if is_last else "│   "
            map_lines.extend(walk_directory(path, prefix + extension))
        elif path.endswith(".py"):
            # Extract symbols for python files
            symbols = generate_ast_summary(path)
            if symbols:
                extension = "    " if is_last else "│   "
                for sym in symbols:
                    map_lines.append(f"{prefix}{extension}{sym}")
                    
    return map_lines

def main():
    print(f"Generating Repo Map for {PROJECT_ROOT}...")
    
    map_content = [
        "# Repository Map",
        "> This file is auto-generated by `scripts/generate_repo_map.py`. Do not edit manually.",
        "> It provides the AI with structural context of the codebase without exceeding token limits.",
        "",
        "```text",
        PROJECT_ROOT.name
    ]
    
    map_content.extend(walk_directory(PROJECT_ROOT))
    map_content.append("```")
    
    # Ensure docs dir exists
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(map_content))
        
    print(f"Repo Map successfully written to {OUTPUT_FILE}")

if __name__ == "__main__":
    main()
